### ISSUE TITLE
[Question] Why not using Oban for background jobs?

### ISSUE THREAD

**Issue by olivierobert** [Goose97/google_scraper#3]
## Issue

The current Task Queue and Worker implementation is quite complex (and not covered by any tests 😱). At the same time, https://github.com/sorentwo/oban is a widely used solution for implementing PostgresQL-based background job processing that could have solve the needs in this application

> **Note**
> Our team wrote about Oban: https://nimblehq.co/blog/the-journey-on-choosing-elixir-background-job-tooling

**Comment by Goose97** [comment]
I laid out some initial test cases [here](https://github.com/Goose97/google_scraper/blob/main/backend/test/google_scraper/scraping/task_queue_test.exs). I'll admit that the test suite is nowhere near throughout 😅. I'm planning to add some more to cover the failure handling/retry path.

Regarding Oban, yeah I knew about it for quite some time, a solid library. The reason I didn't choose its because even though I knew about Postgres-backed task queues for quite some time, I never learn about it properly. So I guess it's a good learning opportunity to try implementing one. If this is a production-grade application, I surely will go with Oban here.
