### ISSUE TITLE
[Question] Why not using Phoenix LiveView?

### ISSUE THREAD

**Issue by olivierobert** [Goose97/google_scraper#5]
## Issue

The current implementation relies on (e.g, https://github.com/Goose97/google_scraper/blob/main/frontend/src/api.tsx#LL1C1-L1C1) and duplicates a lot of functionality provided by https://github.com/phoenixframework/phoenix_live_view. It also results in a lot of complexity in handling the UI updates: https://github.com/Goose97/google_scraper/blob/main/frontend/src/ScrapingPage/index.tsx#L118-L134. So what are the advantages of the current implementation over using built-in features of Phoenix?

**Comment by Goose97** [comment]
Mostly because I'm pretty inexperienced when it comes to Phoenix LiveView. And by the time I get to the client bits, there's not much time left, so I went with the stack that I'm more comfortable with.

Regarding to question about advantages over React:
As I said above, I have limited experience with LiveView, so I don't think I can comment anything here. If I have to say, then a) React should be more suitable with complex applications and b) interoping with the JS ecosystem will be easier.

But again, React might be an overkill for this project. Definitely will look into LiveView for my next personal project.
